### ISSUE TITLE
Allow generic social entries

### ISSUE THREAD

**Issue by flxzt** [pavelzw/moderner-cv#1]
Hi, thanks for creating this template. I am porting my CV from LaTeX Modern-CV and it translates quite nicely.

There is one paper cut I am experiencing though:

In my old CV, I added some additional social entries like an URL to my blog.
In this template if it is not a supported social platform the entry gets ignored entirely ([here](https://github.com/pavelzw/moderner-cv/blob/1cd833922fe5afa23b87c3ff5aa9b77517743234/lib.typ#L31))

It would in my opinion be a nice improvement if custom entries can be added, falling back to displaying the contents of those entries without an icon. This would greatly improve the flexibility of the template.

**Comment by pavelzw** [comment]
I added the ability to define custom socials in #1

```typ
#show: moderner-cv.with(
  name: "Jane Doe",
  lang: "en",
  social: (
    // predefined socials: phone, email, github, linkedin, x, bluesky
    email: "jane.doe@example.com",
    github: "jane-doe",
    linkedin: "jane-doe",
    // custom socials: (icon, link, body)
    // any fontawesome icon can be used: https://fontawesome.com/search
    website: ("link", "https://example.me", "example.me"),
  ),
)
```
